import discord
from discord import app_commands
from discord.ext.commands import Bot, GroupCog
from discord_py_utilities.messages import send_message, send_response

from classes.access import AccessControl
from classes.configdata import ConfigData
from classes.warnings.punishments import Punishments
from data.config.mappings import Channels, WarningConfigs
from database.transactions.ConfigTransactions import ConfigTransactions
from database.transactions.WarningTransactions import WarningTransactions
from view.modals.inputmodal import send_modal
from view.v2.WarningManager import WarningManager


class Warnings(GroupCog) :

	def __init__(self, bot: Bot) :
		self.bot = bot

	# Add warning
	@app_commands.command(name="warn", description="Creates a warning for the selected member")
	@app_commands.checks.has_permissions(manage_messages=True)
	async def warn(self, interaction: discord.Interaction, member: discord.Member, kick: bool = False,
	               inform: bool = True) :
		"""
		Create a warning for the selected member with the options to inform them, kick them, and permanent logging.

		Permissions:
		- manage messages
		"""

		# prepare the configs
		warning_archive = await ConfigData().get_channel(interaction.guild, Channels.WARNING_LOG)
		if not warning_archive :
			return

		# Prompt for message
		reason = await send_modal(interaction, f"Creating warning, it will show up in {warning_archive.mention}",
		                          ephemeral=True)

		# Prepare a simple embed
		count = WarningTransactions().count_warnings(member.id, interaction.guild.id) + 1

		embed = discord.Embed(
			title=f"Warning from {interaction.guild.name}",
			description=reason,
			colour=discord.Colour.blue(),
		)
		embed.set_footer(text=f"Current Warnings: {count}")
		# inform user
		if inform :
			try :
				if not member.dm_channel :
					await member.create_dm()
				await member.send(
					f"-# This message was generated by {interaction.guild.name}, please open a support ticket with the server if you think this warning is invalid.",
					embed=embed)
			except discord.Forbidden :
				await send_message(interaction.channel,
				                   f"Failed to inform {member.mention}, I am unable to dm them because their DMs are closed, they have left the server or I am blocked.")

		# log warning
		await WarningTransactions().add(interaction, member, embed, reason, channel=warning_archive)
		# check if kick is true
		if kick :
			try :
				await send_message(member,
				                   f"You've been kicked from {interaction.guild.name}, you may rejoin once your behavior improves.")
				await member.kick(reason=reason)
			except Exception as e :
				await send_message(interaction.channel, f"Failed to kick {member.mention}, the reason is {e}")

		if kick or not AccessControl().is_premium(interaction.guild.id):
			return
		await Punishments().check_punishments(interaction.guild, member)

		# define punishments

	# view/manage warnings UI (Edit, Delete, Add Evidence)
	@app_commands.command(name="manage", description="View and manage the warnings the user has.")
	@app_commands.checks.has_permissions(manage_messages=True)
	async def manage(self, interaction: discord.Interaction, user: discord.User) :
		"""
		Allows you to manage the warnings you have, as well as add evidence or even take actions against the user.

		Permissions:
		- manage messages
		"""
		if not user :
			return await send_response(interaction, f"You must specify a user to view.")

		warnings = WarningTransactions().get_all(user_id=user.id, guild_id=interaction.guild.id)
		if len(warnings) < 1 :
			return await send_response(interaction, f"No warnings found for `{user.name}`.", ephemeral=True)
		view = WarningManager(user=user, warnings=warnings)
		return await send_response(interaction, "", view=view)

	@app_commands.command(name="punishments", description="Define automated punishments based on warning count")
	@app_commands.choices(option=[
		app_commands.Choice(name=punishment.name.title(), value=punishment.value) for punishment in WarningConfigs
	])
	@app_commands.checks.has_permissions(manage_guild=True)
	@AccessControl().check_premium()
	async def punishments(self, interaction: discord.Interaction, option: app_commands.Choice[str], warning_count: int) :
		"""
		Define automated punishments based on warning count. To remove input 0 in warning_count

		Permissions:
		- manage guild
		- Premium
		"""
		key = option.value
		if warning_count < 1:
			ConfigTransactions().config_unique_remove(interaction.guild.id, key)
			return await send_response(interaction, f"Successfully removed {key} from the warning consequences list", ephemeral=True)
		ConfigTransactions().config_unique_add(interaction.guild.id, key, warning_count)
		return await send_response(interaction, f"Successfully added {key} from the warning consequences list. After {warning_count} they will receive this punishment.", ephemeral=True)





async def setup(bot: Bot) :
	await bot.add_cog(
		Warnings(bot),
	)
