"""Add Timestamps to all tables

Revision ID: 1b18c6d995cc
Revises: 98b39ea5d554
Create Date: 2026-05-15 01:07:05.763848

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b18c6d995cc'
down_revision: Union[str, None] = '98b39ea5d554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeal_msgs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appeal_msgs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appeals', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appeals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ban_messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ban_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ban_reasons', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ban_reasons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bans', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('config', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('config', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flagged_terms', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flagged_terms', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proof', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proof', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('servers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('warnings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('warnings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warnings', 'updated_at')
    op.drop_column('warnings', 'created_at')
    op.drop_column('staff', 'updated_at')
    op.drop_column('staff', 'created_at')
    op.drop_column('servers', 'created_at')
    op.drop_column('proof', 'updated_at')
    op.drop_column('proof', 'created_at')
    op.drop_column('flagged_terms', 'updated_at')
    op.drop_column('flagged_terms', 'created_at')
    op.drop_column('config', 'updated_at')
    op.drop_column('config', 'created_at')
    op.drop_column('bans', 'updated_at')
    op.drop_column('ban_reasons', 'updated_at')
    op.drop_column('ban_reasons', 'created_at')
    op.drop_column('ban_messages', 'updated_at')
    op.drop_column('ban_messages', 'created_at')
    op.drop_column('appeals', 'updated_at')
    op.drop_column('appeals', 'created_at')
    op.drop_column('appeal_msgs', 'updated_at')
    op.drop_column('appeal_msgs', 'created_at')
    # ### end Alembic commands ###
