"""Add date override to Bans table

Revision ID: 98b39ea5d554
Revises: ecc239a088a5
Create Date: 2026-04-11 14:03:16.053264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b39ea5d554'
down_revision: Union[str, None] = 'ecc239a088a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('date_override', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bans', 'date_override')
    # ### end Alembic commands ###
