"""update server table

Revision ID: 9b0d48a7677b
Revises: adb569f2001d
Create Date: 2025-11-30 14:45:18.301718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b0d48a7677b'
down_revision: Union[str, None] = 'adb569f2001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('premium', sa.DateTime(timezone=True), nullable=True))
    op.add_column('servers', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.alter_column('servers', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('servers', 'owner_id')
    op.drop_column('servers', 'premium')
    # ### end Alembic commands ###
