"""Add new column to Bans table

Revision ID: ecc239a088a5
Revises: 9b0d48a7677b
Create Date: 2026-04-04 03:39:13.336770

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecc239a088a5'
down_revision: Union[str, None] = '9b0d48a7677b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('edited',
                  sa.DateTime(timezone=True), nullable=True))
    op.add_column('bans', sa.Column('edited_by', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bans', 'edited')
    op.drop_column('bans', 'edited_by')
    # ### end Alembic commands ###
